# Generated by Django 3.2.4 on 2024-08-14 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_private', models.BooleanField()),
            ],
        ),
    ]
